### ISSUE TITLE
CMake modules & config

### ISSUE THREAD

**Issue by manuelk** [wdas/ptex#17]
It would be nice to:
- Wherever possible switch dependencies to git submodules (zlib): users wouldn't have to locate, build & configure anymore for those
- Author PtexConfig.cmake file so that Ptex itself can be embedded as a git module into other projects (glfw does this, but seems to be missing some pieces)

**Comment by davvid** [comment]
PR #35 which provides a ptex-config.cmake.  That'll tackle that aspect.

**Comment by davvid** [comment]
Ptex now exports its targets so you can do `find_package(Ptex REQUIRED)` and it'll find an installed ptex library using cmake's builtin conventions.  Feel free to reopen this issue if there are other concerns.

The cmake approach is you have to install ptex somewhere, for example `make install prefix=/opt/ptex/example`  and then arrange to have `/opt/ptex/example` in your `$CMAKE_PREFIX_PATH` environment variable and cmake will be able to find it.  There are [other ways to control the path lookup as well](https://cmake.org/cmake/help/v3.8/command/find_package.html).

`zlib-devel` is a really easy dependency for Linux and macos users so that's not really high on our priority list.  We are using pkg-config via cmake to find zlib, so it should be pretty easy for you to get it building using whatever zlib you have available.

I'm not really a fan of bundling all this stuff into ptex itself personally.  It's a maintenance burden and if we did do it then we'd be on the hook to periodically update our submodule for security fixes, etc. etc.

Use a package manager on Linux and this is a non-issue.

Taking this request its logical conclusion -- should we also be responsible for bundling the compiler we use, the cmake version we require, GNU make, python, and other misc. bits?  I don't think so.  At some point we have to be able to rely on external dependencies.
