### ISSUE TITLE
Release tarball is unable to determine what version it is

### ISSUE THREAD

**Issue by sambler** [wdas/ptex#41]
In a release tarball, there is no `version` file and no git files to query. This means we need to manually specify the `PTEX_VER` during config.

Without defining `PTEX_VER` the replace on line 48 fails.

**Comment by davvid** [comment]
Hi @sambler we don't "officially" support the release tarballs but we'll look into improving this in the future.  For now it's expected that you provide a version file yourself since it's out-of-band metadata that will not be present in a `git archive` export of the project (aka github's zip downloads).

So after you unzip and enter the directory, assuming you downloaded the `v1.2.3` tarball, run `echo v1.2.3 >version` and that'll do the trick for now.

I'll leave this issue open until we have a commit that adds a fallback scheme for the version that will prevent users from running into this.
