### ISSUE TITLE
Linking Error Windows VS 2019

### ISSUE THREAD

**Issue by jonassorgenfrei** [wdas/ptex#44]
Hey,

I tried building ptex for Windows x64 with VS 2019.
Unfortunetly I got a linking error for the Symbol: h2fTable and fthTable. When building the halftest Projekt.

LNK2001	 ""public: static unsigned int * Ptex::v2_3::PtexHalf::h2fTable" (?h2fTable@PtexHalf@v2_3@Ptex@@2PAIA)".	halftest	D:\Bibliotheken\ptex\build\src\tests\halftest.obj	1	
LNK2001	 ""public: static unsigned short * Ptex::v2_3::PtexHalf::f2hTable" (?f2hTable@PtexHalf@v2_3@Ptex@@2PAGA)".	halftest	D:\Bibliotheken\ptex\build\src\tests\halftest.obj	1	

I was able to fix this problem by adding the line:
#include "PtexHalfTables.h"
under 
#include "PtexHalf.h"
In halftest.cpp 
But I'm not sure if this is "best practice".

Best Regards,
Jonas

**Comment by davvid** [comment]
Hi @jonassorgenfrei this seems like a symbol visibility issue to me.

I don't have a Windows machine to verify, so we'll need your help to track down the correct fix.

My understanding from the error message is that the linker does not see the half table symbols. My explanation for why that might be is that on Windows symbol visibility is hidden by default.

In PtexHalf.h try adding `PTEXAPI` on the line right above `struct PtexHalf {`  (~line 87) and try rebuilding the ptex library.  In theory that should make the PtexHalf symbols visible.


You may not that around line 160-121 some symbols (including the half tables members) were already marked visible, so it is kinda surprising that this is needed, but hopefully that's the root cause and fixes it.  Let me know if marking that class with PTEXAPI fixes the issue.


Including PtexHalfTables.h is not advised -- those symbols are intended to be provided by the ptex library itself and you may later get errors about multiply-defined symbols if we went down that route.

Let me know whether adding the `PTEXAPI` visibility macro fixes this issue for you.

**Comment by jonassorgenfrei** [comment]
Hey @davvid,
I tried building it again with the PTEXAPI Marco above the PtexHalf struct. 
Unfortunatley this didn't fix the problem. 

I then accidentally rebuild the Ptex_static project and was able to build halftest afterwards.
I figured out that when building the static libraries and linking against them everything works like a charm, 
But building the dynamic libraries seems to produces the problem, may be its just a problem with Windows or Visual Studio (2019 and -17) As if the content of the Ptex.dll couldn't be found. 
Shall halftest link against the dynamic or the static libraries? They were build at the same location with the same name, overwritting each other.

**Comment by davvid** [comment]
Looking at the build scripts, it's setup to build either static or dynamic.

We default to the following:

        PTEX_BUILD_STATIC_LIBS=ON
        PTEX_BUILD_SHARED_LIBS=ON

For Windows, I suspect that building the static library will work better.  Does it work if you tweak the default (defined in `CMakeLists.txt`) for `PTEX_BUILD_SHARED_LIBS` to `OFF` and rebuild from scratch?

If tweaking that default works then a patch to change the default for Windows might be a good idea.

BTW, I'm a little surprised that it built both and overwrote one.  It's using an `else if` in `src/tests/CMakeLists.txt` so it should only consider one of the two variants.  Nonetheless, hopefully tweaking that default should be sufficient.  Let me know how that goes.

**Comment by jonassorgenfrei** [comment]
Yeah switching PTEX_BUILD_SHARED_LIBS to off worked perfectly.

Well I think building both comes from the src/ptex CMakeLists; there is no switch between Static and Shared and both have the same output name (line 22 and 35).
The CmakeLists in src/test seems to only link the already build static or shared library.

**Comment by davvid** [comment]
@jonassorgenfrei please test the `windows-static-libs` branch in my fork -- it should DTRT by default now.  Let us know how that goes.
