### ISSUE TITLE
uninstall ptex

### ISSUE THREAD

**Issue by zurrehma** [wdas/ptex#53]
How can I uninstall ptex? actually I am getting this below error and want to remove everything.
`install/bin/ptxinfo: error while loading shared libraries: libPtex.so: cannot open shared object file: No such file or directory`

**Comment by davvid** [comment]
It looks like it's working fine, you just have to set your `LD_LIBRARY_PATH` to point to the `install/lib` directory.

You could place vx https://github.com/davvid/vx in your path and use `vx ./install ptxinfo` to run the tool in a subshell where the `./install/lib` directory is in your library path, or just set the variable manualy:


```
LD_LIBRARY_PATH=$PWD/install:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH

./install/bin/ptxinfo

```

and it'll run just fine.  Otherwise, you can just `rm -rf ./install` and that'll remove the stuff you built locally.

If you used the `make install` steps from the `Makefile` (which it looks like you did) then you can also just run `make uninstall` and it'll remove the files for you.  The instructions in the README don't install anything outside of the `./install` directory; it's self-contained.
