### ISSUE TITLE
Exported cmake config files have wrong version (if doing out of source dir build?)

### ISSUE THREAD

**Issue by lgritz** [wdas/ptex#60]
When I check out Ptex at v2.4.0 and do a CMake-based build, I seem to end up with a $PREFIX/share/cmake/Ptex/ptex-version.cmake that says,

    set(PACKAGE_VERSION "2.3")

whereas I would expect this to say "2.4.0".

This seems to be because it's falling into the default case of setting PTEX_VER to "v2.3.X" at [CMakeLists.txt#L64](https://github.com/wdas/ptex/blob/main/CMakeLists.txt#L64)

Now, I should point out that I was trying to build into a directory that was a sibling (rather than a child) of the cloned ptex repo. Like this:

    $ git clone https://github.com/wdas/ptex -b v2.4.0 ptex
    $ cmake -B build -S ptex 
    $ cmake --build build --target install

I tried it where the build is done *inside* the checked-out repo:

    $ git clone https://github.com/wdas/ptex -b v2.4.0 ptex
    $ cd ptex
    $ cmake -B build -S .
    $ cmake --build build --target install

And in this case, it works!

I would really like to build in the first way if possible. I'm not sure why the logic in CMakeLists is failing to figure out the version in this case.

There are three possible fixes. From laziest to most robust:

1. Just change the default from "v2.3.X" to "v2.4.X" since it's a 2.4 release now.

2. Fix whatever is broken about the version parsing logic.

3. Overhaul the version logic to the more standard practice of simply opening with
```
project(Ptex VERSION 2.4.0)
```
   and then there is no more logic necessary, this is the one and only place where the version needs to be defined, since the  `project` function in CMake automatically parses the version and set PROJECT_MAJOR_VERSION (and MINOR, PATCH, TWEAK if supplied) and for that matter, also Ptex_MAJOR_VERSION, etc. (based on your project name). This business of querying git for the latest tag, and then trying to extract the major/minor version numbers from that string... unusual, to say the least, and apparently a bit error prone.

Also, it would be nice if all places with versions define all 3 levels (major, minor, and patch) -- including in the exported cmake config as well as in PtexVersion.h -- since that's the way you're tagging releases.

**Comment by lgritz** [comment]
As a project maintainer myself, I feel like I should apologize for just dumping this in your lap instead of fixing it myself and submitting a PR. But since I haven't had the need to send PRs to Ptex before, I would need to first get a proper CLA signed by my employers, which is probably a minimum turnaround of at least a couple weeks (because bureaucracy).

**Comment by davvid** [comment]
Thanks for the notes. We should definitely update the default fallback version (because that's good to do in general with the new minor release) ~ I'll loop back tomorrow and push up an update that does that.

Having to maintain that file is a bit of a burden so the idea behind querying git is similar to the python `setuptools_scm` idea since internally we always build with a git repo available. That's just the context behind why we do it internally. Making things easy for external consumption is nonetheless a priority.

We do provide an escape hatch specifically for packagers that build from a tarball or non-git scenario. If you do this:

```
echo v2.4.0 >version
```

... then the parsing logic will read the version number from the `version` file. I'll leave this issue open so that we can do two things before we close it:

* Mention the version escape hatch in the README so that packagers can know that this is available without having to reverse-engineer our cmake files
* Update the hard-coded fallback version number

**Comment by davvid** [comment]
I've always wished that github provided a way to inject stuff into the zip/tar files that they make available from git tags. What most projects do is have a `make dist` or similar target that generates a "distribution tarball".

If you take a look at Git's `make dist` target, you'll see that's exactly what they do:

https://github.com/git/git/blob/master/Makefile#L3129

They support the same `version` file idea as Ptex. When you build Git from a git repo it queries git for the version, just like we do ~ so it's not that weird ;-) just a little gitty.

If github allowed a way to inject stuff into a release tarball then this would be a non-issue since we could basically do the same as providing a `make dist` tarball. Having to also upload specially-crafted tarballs to github was too much of a burden, and it doesn't eliminate the fact that users can download zips directly from github, thus this slight friction.

Anyways, just notes in case you're curious where this convention originated.

**Comment by lgritz** [comment]
Ah, interesting background. I see now what you're trying to do. I should have clarified that I meant, "it's weird for CMake," in which it's conventional to declare the version with the `project()` call and everything else flows from there.

**Comment by davvid** [comment]
The fallback version was updated in b583318a9fc7b7c600a9ad2de6469fae84f76324. Turns out we already mention this in the README.  It also has notes for the maintainer about updating the hard-coded version number which I forgot to read ;-) but won't next time. Thanks Larry
