### ISSUE TITLE
How do I run the software?

### ISSUE THREAD

**Issue by CombatKnight4** [wdas/ptex#70]
I don't know how to run the software.

**Comment by davvid** [comment]
Ptex is more of a sofware library that is used for developing other applications. Besides the Ptex C++ SDK, there is the ptexutils project which contains ptex-related utilities, eg. ptxview for viewing ptex .ptx files.

https://github.com/wdas/ptexutils/

You'll need to have ptex installed in order to build ptexutils, for example.

ptex files can be used with renderers such as [Renderman](https://renderman.pixar.com/) and [V-Ray](https://docs.chaos.com/display/VFBlender/Ptex).

Ptex is supported in various tools, eg. mari, 3dcoat, houdini, mudbox and maya.

https://3dcoat.com/documentation/manual/workspaces-rooms/paint/texture-painting-and-modes/ptex-painting/

https://www.youtube.com/watch?v=yFwoeOLECe4

https://www.sidefx.com/docs/houdini/shade/ptex.html

https://learn.foundry.com/mari/content/user_guide/ptex/ptex.html

If you'd like to build the Ptex library and tools then the easiest way is to use a Linux machine and run `make` to build the tools. It's a little more involved on other platforms.

Hope that helps!
